### PR TITLE
Duplication layer of groundwater for specific organisation

### PR DESCRIPTION
**Pull request by meomancer**
This will fix : 
- https://github.com/kartoza/IGRAC-GGIS/issues/561

The updates:
- Mapstore Client : https://github.com/kartoza/geonode-mapstore-client/tree/4.0.9
- Mapstore : https://github.com/kartoza/MapStore2/commit/04e9f24de027b6d14cce65dea5e3257c61920928
- GWML2 : https://github.com/kartoza/IGRAC-WellAndMonitoringDatabase/commit/437be94495417879bf3276636efcbaed68612f46

### CODE REVIEW

**Comment by meomancer** [comment]
On geoserver, Groundwater_Well and Groundwater_Well_GGMN, add this sql:
```
where groups@>'{%GROUP%}'
```
Selection_023

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Here how it works:

We have column groups on organisation
Selection_017

We can change it or on admin
Selection_018
Selection_019

The group is in here:
https://ggis.un-igrac.org/en-us/admin/groups/groupprofile/
We can add it manually

Now we assign
**Geological Survey Canada (Canada)** to group [USA] and also [Canada and USA]
And also
**U.S. Geological Survey (United States)** to group [Canada and USA]

Selection_024

Use case in here, we need to create 2 maps that contains:
- 1. Contains well : Geological Survey Canada (Canada)
- 2. Contains well : Geological Survey Canada (Canada) and U.S. Geological Survey (United States)

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, how do you create and name the new maps?

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 

It is in here
Selection_001

For naming, it is on save as....
Selection_002

How the solution on this PR @ArnaudIGRAC ?

**Comment by ArnaudIGRAC** [comment]
hi Irwan, my question is: how do you create the 3 maps in your post above? 

I am not sure about this solution. It seems that the maps originally contain all the data, until you filter them when you assign it to a specific group. I would prefer if the layer was automatically created with the right selection of data, which you could define in Admin.

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
We can't create multiple layer on geonode from 1 source of layer on geoserver, there is no duplication options on geonode.
And also if we want to have multiple layer, we need to create the layer on geoserver instead for specific filter.

This PR basically another option to handle it without creating layer on geoserver.
We can create multiple map from Well and Monitoring Data or GGMN Data, and assign group on the map to automatically filter the data.

**Comment by ArnaudIGRAC** [comment]
Thanks Irwan. Then I think I would prefer to create new layers in GeoServer. Would I be able to do that, if you show me how?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
i think there is another option to update implement it
i will create simple form that will just:
- Type selection : ["Well and Monitoring Data", "GGMN"]
- Group : The group that will be linked to the layer

And after that, the form will automatically create layer to geoserver, and repull to geonode

I would like to implement this method

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
I have updated the flow
Now we can duplicate the layer in the geonode, and it will handle layer creation automatically (not on Map anymore)
So we have dedicated layer on it

Selection_003

Here is the flow:
Creating Canada and USA monitoring layer
https://drive.google.com/file/d/1CbdpKFM782khUbB8wj8p7qwh1OfCbLOj/view?usp=sharing

Creating Gambia layer
https://drive.google.com/file/d/1w8Jmfk839M2gLlzLBS68UiDo1xJyYgRk/view?usp=sharing

**Note**
- I'm still using Group as linking to new layer, because it will be easy to change the organisation without updating layer.
  So we can just change add/remove the organisation in the group of layer to change the data filter

- Or do you think we can just use Organisations selection in the form? 
  For this, i need to create form to update this duplicated layer to change the selected organisations to apply it on the geoserver

**Comment by ArnaudIGRAC** [comment]
Thanks Irwan, that is better! I would indeed use Organizations in the form, instead of groups. Would it be possible to move the form to Admin (Django)? I don't really like to have it in the main Geonode menu. Could we then have an overview of all layers, and all organizations linked to a layer?

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Here is the form with organisations
https://drive.google.com/file/d/1Qe7CWO5F_xg3ZwXqnlEZGxrAfaJUulME/view?usp=sharing

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
This should be final one

- For is on admin site "Groundwater Well" under "IGRAC" app, or using this link later "/en-us/admin/igrac/groundwaterlayer/"
- We can also edit it (change organisations and the layer type between well and monitoring data or ggmn)

Could you check it? 
https://drive.google.com/file/d/12eGuFWQrhfyMWEoe0xJRRANssevnnP5y/view?usp=sharing


If it is good, i will deploy it to staging tomorrow

**Comment by ArnaudIGRAC** [comment]
I like it, please go ahead!

**Pull request merged**
